// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"github.com/google/wire"
	"github.com/possibities/gin-core/internal/app"
	"github.com/possibities/gin-core/internal/dependency"
	"github.com/possibities/gin-core/internal/event"
	"github.com/possibities/gin-core/internal/handler"
	"github.com/possibities/gin-core/internal/repository"
	"github.com/possibities/gin-core/internal/router"
	"github.com/possibities/gin-core/internal/scheduler"
	"github.com/possibities/gin-core/internal/service"
	"github.com/possibities/gin-core/internal/worker"
	"github.com/possibities/gin-core/pkg/cache"
	"github.com/possibities/gin-core/pkg/config"
	"github.com/possibities/gin-core/pkg/i18n"
	"github.com/possibities/gin-core/pkg/jwt"
	"github.com/possibities/gin-core/pkg/logger"
	"github.com/possibities/gin-core/pkg/metrics"
	"github.com/possibities/gin-core/pkg/mq"
	"github.com/possibities/gin-core/pkg/tracing"
)

// Injectors from wire.go:

func InitializeApp(cfg *config.Config) (*app.App, func(), error) {
	logger, cleanup, err := pkglogger.New(cfg)
	if err != nil {
		return nil, nil, err
	}
	provider, cleanup2, err := tracing.New(cfg, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	pool, cleanup3, err := worker.NewPoolProvider(cfg, logger)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	registry := metrics.New(pool)
	db, cleanup4, err := repository.NewDB(cfg, provider, registry)
	if err != nil {
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	client, cleanup5, err := cache.NewRedisClient(cfg, provider)
	if err != nil {
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	v := dependency.NewDependencyCheckers(cfg, db, client)
	healthHandler := handler.NewHealthHandler(v)
	sessionHandler := handler.NewSessionHandler()
	userRepository := repository.NewUserRepository(db)
	outboxRepository := repository.NewOutboxRepository(db)
	txManager := repository.NewTxManager(db)
	readThroughStore := cache.NewReadThroughStore(cfg, client, registry)
	keyspace := cache.NewKeyspace(cfg)
	bus := event.NewBus(logger, pool)
	userService := service.NewUserService(userRepository, outboxRepository, txManager, readThroughStore, keyspace, bus)
	userHandler := handler.NewUserHandler(userService)
	auditLogRepository := repository.NewAuditLogRepository(db)
	auditService := service.NewAuditService(auditLogRepository)
	adminHandler := handler.NewAdminHandler(auditService)
	slidingWindowLimiter := cache.NewSlidingWindowLimiter(client)
	redisTokenStore := pkgjwt.NewRedisTokenStore(keyspace, client)
	manager := pkgjwt.NewManager(cfg, redisTokenStore, redisTokenStore)
	syncedEnforcer, cleanup6, err := dependency.NewRBACEnforcer(cfg, db)
	if err != nil {
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	translator, err := i18n.New()
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	engine := router.NewEngine(cfg, healthHandler, sessionHandler, userHandler, adminHandler, keyspace, slidingWindowLimiter, manager, syncedEnforcer, translator, registry, provider)
	server := app.NewHTTPServer(cfg, engine)
	distributedLocker := cache.NewDistributedLocker(client, keyspace)
	publisher, cleanup7, err := mq.NewPublisher(cfg, provider)
	if err != nil {
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	outboxDispatcher := event.NewOutboxDispatcher(cfg, logger, outboxRepository, publisher, registry)
	schedulerScheduler, err := scheduler.NewScheduler(cfg, logger, distributedLocker, outboxDispatcher, registry)
	if err != nil {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	userProfileUpdatedSubscriber := service.NewUserProfileUpdatedSubscriber(bus, auditService)
	appApp := app.NewApp(server, healthHandler, schedulerScheduler, outboxDispatcher, pool, userProfileUpdatedSubscriber, logger)
	return appApp, func() {
		cleanup7()
		cleanup6()
		cleanup5()
		cleanup4()
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var providerSet = wire.NewSet(pkglogger.New, worker.NewPoolProvider, wire.Bind(new(metrics.WorkerQueue), new(*worker.Pool)), metrics.New, tracing.New, event.NewBus, event.NewOutboxDispatcher, wire.Bind(new(event.Publisher), new(*event.Bus)), repository.NewDB, repository.NewAuditLogRepository, repository.NewOutboxRepository, repository.NewTxManager, repository.NewUserRepository, cache.NewRedisClient, cache.NewDistributedLocker, cache.NewKeyspace, cache.NewReadThroughStore, cache.NewSlidingWindowLimiter, wire.Bind(new(cache.ReadStore), new(*cache.ReadThroughStore)), i18n.New, mq.NewPublisher, pkgjwt.NewRedisTokenStore, wire.Bind(new(pkgjwt.BlacklistStore), new(*pkgjwt.RedisTokenStore)), wire.Bind(new(pkgjwt.RefreshTokenStore), new(*pkgjwt.RedisTokenStore)), pkgjwt.NewManager, dependency.NewRBACEnforcer, dependency.NewDependencyCheckers, handler.NewHealthHandler, handler.NewSessionHandler, service.NewAuditService, service.NewUserProfileUpdatedSubscriber, service.NewUserService, handler.NewUserHandler, handler.NewAdminHandler, scheduler.NewScheduler, router.NewEngine, app.NewHTTPServer, app.NewApp)
